### ISSUE TITLE
Will you release a pre-built package for windows x64 ?

### ISSUE THREAD

**Issue by QuantumLiu** [intel/onnxruntime#114]
**System information**
- ONNX Runtime version (you are using):
- onnxruntime 1.9.0
- win10 x64

**Comment by sfatimar** [comment]
Do you wish to use the openvino flavour of OnnxRuntime ?

**Comment by natelowry** [comment]
@QuantumLiu I think the latest release should run that scenario just fine.

https://github.com/intel/onnxruntime/releases/tag/v4.0
