### ISSUE TITLE
GPU inference not working

### ISSUE THREAD

**Issue by G2020sudo** [intel/onnxruntime#120]
**Describe the bug**
Performing inference with CPU vs GPU the CPU and GPU/Render utilizations never change.

CPU: 
python3 yolov4.py --image mypic.jpg --device CPU_FP32

GPU
python3 yolov4.py --image test-image-1_yolo_out_py.jpg --device GPU_FP32
python3 yolov4.py --image test-image-1_yolo_out_py.jpg --device GPU_FP16

Verifying  utilizations with intel_gpu_top and top there are no observable differences. There are also no errors displayed from yolov4.py.

The yolo model is pulled from OMZ as indicated in https://github.com/intel/onnxruntime-inference-examples/tree/main/python/OpenVINO_EP/yolov4_object_detection.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 host. Using Docker image openvino/onnxruntime_ep_ubuntu18:2021.4.2
- ONNX Runtime installed from (source or binary): In the Docker image installed ONNX-Runtime 1.10 from https://github.com/intel/onnxruntime/releases/download/v3.4/ubuntu18-v3.4-python3.7-whl.zip
- ONNX Runtime version: 1.10.0
- Python version: 3.7
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: KBL  i7-8559U

**To Reproduce**
- Describe steps/code to reproduce the behavior.
In the Docker image also installed:
pip3 install torchvision onnx==1.10.0 
pip3 install https://download.pytorch.org/whl/cpu/torch-1.9.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
pip3 install tensorflow
pip3 install redis
pip3 install opencv-python

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/yolov4/model/yolov4.onnx

**Expected behavior**
GPU / Render utilization should increae while CPU utilization reduce. Currently the CPU utilization never changes.

**Screenshots**
Can provide if needed

**Additional context**
None

**Comment by MaajidKhan** [comment]
Hi @G2020sudo . Sorry for late reply. we don't track issues from here. In the future, please create your issues with OpenVINO EP here as specified in our documentation page - https://github.com/microsoft/onnxruntime/issues

To answer your query, Yolov4 model is not fully supported on GPU with OpenVINO EP with OpenVINO 2021.4. The resize operator is unsupported and the model is fully falling back to default CPU EP (MLAS) which again runs on CPU.

This is the reason, you don't see any reduction of CPU utilization as the model is not getting ran on iGPU.

we have a upcoming OpenVINO-EP v4.0 release (Apr 1st week) which will support the latest upcoming OpenVINO 2022.1 version. With this release of OpenVINO version, the yolov4 model will be fully supported on GPU as well and will fully run on Intel iGPU.

Look out for this release, we will also be publishing new python wheels and docker images as well.
