### ISSUE TITLE
[Build] provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "xxx/onnxruntime_providers_openvino.dll"

### ISSUE THREAD

**Issue by DennisJcy** [intel/onnxruntime#324]
### Describe the issue

Hello
I meet the problem when build the ort with openvino.And I make sure that i have copy the dll to the root.
![image](https://github.com/intel/onnxruntime/assets/106725464/42e0c8e6-f8a5-4b51-acc0-edd9b83c3355)

### Target platform

Windows

### Build script

Visual Studio 2022 (v143)
Windows SDK 10.0.17763.0

### Error / output

D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\project\Project_C++\YOLO_ONNX\x64\Release\onnxruntime_providers_openvino.dll"

### Visual Studio Version

2022

**Comment by sspintel** [comment]
Hi, Did you try with the OpenVINO environment initialized? i.e, running the setupvars.bat script of the OpenVINO release package before you run your app.

**Comment by DennisJcy** [comment]
Hello, @sspintel  I do that again. I put my powershell log under.It only echo "OpenVINO environment initialized".But I look the script, It seems to be unwork.
![image](https://github.com/intel/onnxruntime/assets/106725464/35f32899-1ead-4dbc-93ee-4a87b55c2238)

![image](https://github.com/intel/onnxruntime/assets/106725464/2c963c78-8ec8-4854-86c0-15ceceb21e00)
