### ISSUE TITLE
Why doesn't onnxruntime-openvino specify the openvino package as a requirement?

### ISSUE THREAD

**Issue by adrianboguszewski** [intel/onnxruntime#357]
### Describe the issue

While installing onnxruntime-openvino via pip, the openvino package is not installed by default. One doesn't know:
1. they must install openvino separetely
2. which version of openvino they must install
unless they look to the release notes/docs (imagine how many people abandon the process at this stage).

### To reproduce

pip install onnxruntime-openvino

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

OpenVINO

**Comment by adrianboguszewski** [comment]
Don't close. The issue hasn't been solved yet as far as I know.

**Comment by henryruhs** [comment]
@adrianboguszewski It's more like a peerDependency - openvino can be installed via conda as well.

**Comment by adrianboguszewski** [comment]
@henryruhs could you elaborate more on what a peer dependency means?

**Comment by adrianboguszewski** [comment]
Still not resolved...

**Comment by henryruhs** [comment]
Should not be resolved anyway... if you don't know what a peer dependency is, why don't you google it?
