### ISSUE TITLE
Where is onnxruntime-openvino==1.19.0

### ISSUE THREAD

**Issue by henryruhs** [intel/onnxruntime#378]
We are locking forward to test "support for up to OpenVINO 2024.1" but cannot find any official or nightly version of onnxruntime-openvino==1.18.0.

Related issue: https://github.com/microsoft/onnxruntime/issues/20870

**Comment by henryruhs** [comment]
Has been released, finally...

**Comment by sfatimar** [comment]
We have released.

**Comment by jatinwadhwa921** [comment]
It is available on "https://pypi.org/project/onnxruntime-openvino/1.19.0/"

**Comment by henryruhs** [comment]
Thanks
